[package]
name = "masks2nifti"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
rand = "0.8.5"
ndarray = "0.15.6"
nifti = "0.14.0"